name: Deploy Angular to S3 + CloudFront

on:
  push:
    branches: [ "main" ]
    paths:
      - "cosmopolish-app/**"   # odpalaj tylko gdy zmienisz coś w appce
  workflow_dispatch: {}

concurrency:
  group: deploy-prod
  cancel-in-progress: true

env:
  AWS_REGION: eu-central-1
  S3_BUCKET: deploy-mm-cosmopolish-app
  CLOUDFRONT_DISTRIBUTION_ID: E3PN9DVUR5C3JB
  BUILD_DIR: cosmopolish-app/dist/cosmopolish-app/browser   # <— UWAGA: z prefiksem folderu

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: cosmopolish-app/package-lock.json

      - name: Install deps
        working-directory: cosmopolish-app
        run: npm ci

      - name: Build Angular (prod)
        working-directory: cosmopolish-app
        run: npx ng build --configuration production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync assets (long cache)
        run: |
          aws s3 sync "$BUILD_DIR" "s3://${{ env.S3_BUCKET }}" \
            --delete \
            --exclude "index.html" \
            --cache-control "public,max-age=31536000,immutable"

      - name: Upload index.html (no cache)
        run: |
          aws s3 cp "$BUILD_DIR/index.html" "s3://${{ env.S3_BUCKET }}/index.html" \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html"

      - name: Invalidate CloudFront (index + root)
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/index.html" "/"
